export enum Pages {
    None = '',
    Home = 'Home',
    Pricing = 'Pricing',
    Register = 'Register',
    SignIn = 'SignIn',
    SignOut = 'SignOut',
    User = 'User',
    Profile = 'Profile',
    MyPlan = 'MyPlan',
    Companies = 'Companies',
    NewCompany = 'NewCompany',
    Company = 'Company',
    Settings = 'Settings',
    Accounts = 'Accounts',
    Account = 'Account',
    NewAccount = 'NewAccount',
    EditAccount = 'EditAccount',
    Inventory = 'Inventory',
    Vouchers = 'Vouchers'
}